Add plan command
konveyor/move2kube-vscode-plugin pull request #1
Opened 2023-03-14 14:10 UTC by swaingotnochill

This commit adds the plan command to the palette. Currently it runs the plan command with default flags on current working directory with help of an async spawn process.

2023-03-14 22:32 UTC, HarikrishnanBalagopal commented on .gitignore
> +node_modules
Probably we can use this https://github.com/github/gitignore/blob/main/Node.gitignore

2023-03-14 22:44 UTC, HarikrishnanBalagopal requested changes
Looks good, have left some comments. PTAL.

2023-03-14 22:44 UTC, HarikrishnanBalagopal commented on out/extension.js.map
> +{"version":3,"file":"extension.js","sourceRoot":"","sources":["../src/extension.ts"],"names":[],"mappings":";;;AAAA,iCAAiC;AACjC,8DAA2D;AAC3D,yDAAuF;AAEvF,SAAgB,QAAQ,CAAC,OAAgC;IACvD,yBAAyB;IACzB,MAA
We should .gitignore the files in the build directory called `out/`

2023-03-14 22:44 UTC, HarikrishnanBalagopal commented on webview-ui/src/index.tsx
> +ReactDOM.render(
We can use the newer React functions like `createRoot` https://reactjs.org/docs/rendering-elements.html#rendering-an-element-into-the-dom

2023-03-14 22:44 UTC, HarikrishnanBalagopal commented on webview-ui/package.json
> +  "name": "hello-world",
change the name to `move2kube-vscode-plugin`

2023-03-14 22:44 UTC, HarikrishnanBalagopal commented on webview-ui/package.json
> +    "react": "^17.0.2",
Use the latest react 18

2023-03-14 22:44 UTC, HarikrishnanBalagopal commented on webview-ui/package.json
> +    "react-dom": "^17.0.2"
use react-dom 18

2023-03-14 22:44 UTC, HarikrishnanBalagopal commented on webview-ui/package.json
> +    "@types/react": "^17.0.33",
same as above

2023-03-14 22:44 UTC, HarikrishnanBalagopal commented on webview-ui/package.json
> +    "@types/react-dom": "^17.0.10",
same as above

2023-03-14 22:44 UTC, HarikrishnanBalagopal commented on out/extension.js
> +    // Create output channel.
The build output directory `out/` needs to be added to `.gitignore`

2023-03-14 22:46 UTC, HarikrishnanBalagopal commented
> This commit adds the plan command to the palette. Currently it runs the plan command with default flags on current working directory with help of an async spawn process.

I thought we were focussing on the `transform` command?

2023-03-15 07:36 UTC, swaingotnochill commented
> > This commit adds the plan command to the palette. Currently it runs the plan command with default flags on current working directory with help of an async spawn process.
> 
> I thought we were focussing on the `transform` command?

Since transform command needs plan, I thought this should be the first step towards it.

2023-03-15 18:36 UTC, HarikrishnanBalagopal commented
> > > This commit adds the plan command to the palette. Currently it runs the plan command with default flags on current working directory with help of an async spawn process.
> > 
> > 
> > I thought we were focussing on the `transform` command?
> 
> Since transform command needs plan, I thought this should be the first step towards it.

No, we can use the single step flow which does not require plan phase.
```
$ move2kube transform -s ./path/to/src/folder
```

2023-03-15 18:43 UTC, HarikrishnanBalagopal requested changes
Just a typo, otherwise looks good. Thanks for making the changes!

2023-03-15 18:43 UTC, HarikrishnanBalagopal commented on package.json
> +  "name": "mov2kube-vscode-plugin",
typo

2023-03-16 16:17 UTC, swaingotnochill commented on package.json
> +  "name": "mov2kube-vscode-plugin",
Okay. I missed it. Sorry for this.

2023-03-16 16:17 UTC, swaingotnochill commented
> > > > This commit adds the plan command to the palette. Currently it runs the plan command with default flags on current working directory with help of an async spawn process.
> > > 
> > > 
> > > I thought we were focussing on the `transform` command?
> > 
> > 
> > Since transform command needs plan, I thought this should be the first step towards it.
> 
> No, we can use the single step flow which does not require plan phase.
> 
> ```
> $ move2kube transform -s ./path/to/src/folder
> ```

I will work on it after we merge this then :)

2023-03-17 10:41 UTC, HarikrishnanBalagopal commented
> > > > > This commit adds the plan command to the palette. Currently it runs the plan command with default flags on current working directory with help of an async spawn process.
> > > > 
> > > > 
> > > > I thought we were focussing on the `transform` command?
> > > 
> > > 
> > > Since transform command needs plan, I thought this should be the first step towards it.
> > 
> > 
> > No, we can use the single step flow which does not require plan phase.
> > ```
> > $ move2kube transform -s ./path/to/src/folder
> > ```
> 
> Ohh. I will start to work on it.

Thanks, also as a side note, don't force push to the PR branch. It makes it very hard to see the update without reviewing the entire code again. Github already allows us to squash all the commits when the PR gets accepted and merged.

2023-03-17 10:42 UTC, HarikrishnanBalagopal approved these changes
LGTM

2023-03-17 10:44 UTC, merged