feat: add output folder to workspace
konveyor/move2kube-vscode-plugin pull request #4
Opened 2023-04-19 09:44 UTC by swaingotnochill

This commit will allow user to choose a quick pick option on transform and customizations to choose to add the output folder to workspace. For now, the output is stored in /home/swaingotnochill/.m2kplugi noutput/output directory. If a directory by name output is already present, the name is further modified as out - timestamp. This allows to store multiple outputs without bothering about overwrite flag or manually deleting it.

2023-04-19 13:10 UTC, HarikrishnanBalagopal requested changes
changes we discussed in today's meeting.
1. Output folder should be a sibling of the Source folder.
```
/a
  /aa
  /ab
after transform in /a/aa
/a
  /aa
  /myproject
  /ab
  ```
2. Slight change to wording of the question
```
Move2Kube will ask a few questions, do you want to answer them in the terminal?

1. Yes (default)
2. No, I will provide a config file
3. Skip all questions
```

2023-04-22 10:08 UTC, swaingotnochill commented
@HarikrishnanBalagopal  Currently the output stays inside a folder named m2kpluginoutput in the same level as the source? This is only so that the user can easily understand the output is generated here. Other reason is that other than "myproject" folder, it also generates files like 
```
m2k-graph.json
m2kconfig.yaml
m2kqacache.yaml
```

So, i thought its better to store them inside a output folder.

Please review.
And i think you have to squash the commits before merging, as the sign off checks are failing for some reason.

2023-04-22 11:00 UTC, HarikrishnanBalagopal commented
> @HarikrishnanBalagopal Currently the output stays inside a folder named m2kpluginoutput in the same level as the source? This is only so that the user can easily understand the output is generated here. Other reason is that other than "myproject" folder, it also generates files like
> 
> ```
> m2k-graph.json
> m2kconfig.yaml
> m2kqacache.yaml
> ```
> 
> So, i thought its better to store them inside a output folder.
> 
> Please review. And i think you have to squash the commits before merging, as the sign off checks are failing for some reason.

yes that sounds good!

btw please sign off on the PR/commit for DCO

2023-04-22 18:19 UTC, HarikrishnanBalagopal approved these changes

2023-04-22 18:20 UTC, merged